name: work-trial-project

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5432/dockert 
    networks:
      - my_network    


  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/public:/market-data-service/frontend/public
      - ./frontend/src:/market-data-service/frontend/src      
      - ./frontend/Dockerfile:/market-data-service/frontend/Dockerfile

    ports:
      - '3000:3000'
    networks:
      - my_network
      

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert
    networks:
      - my_network
    
    
    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - my_network
    
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my_network
    depends_on:
      - zookeeper
    
volumes:
  postgres_data:  

networks:
  my_network:
    driver: bridge

  #database:
  #  image: postgresql:latest
  #  restart: unless-stopped
  #  ports:
   #   - "5432:5432"
 #   env_file:
 #     - .env
    


      
